# Generated by Django 4.2.5 on 2023-10-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentscourse',
            options={'verbose_name': 'оплата', 'verbose_name_plural': 'оплаты'},
        ),
        migrations.AddField(
            model_name='paymentscourse',
            name='checkout_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id оплаты'),
        ),
    ]