# Generated by Django 4.2.5 on 2023-10-11 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentscourse_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=15, verbose_name='статус оплаты')),
                ('payment_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentscourse', verbose_name='оплата')),
            ],
            options={
                'verbose_name': 'статус',
                'verbose_name_plural': 'статусы',
            },
        ),
    ]