# Generated by Django 4.2.5 on 2023-10-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_checkpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentscourse',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ссылка на оплату'),
        ),
    ]