# Generated by Django 4.2.5 on 2023-10-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymentscourse_payment_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpayment',
            name='payment_course',
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='checkout_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id оплаты'),
        ),
    ]