# Generated by Django 4.2.5 on 2023-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_city_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('staff', 'staff')], max_length=5, null=True, verbose_name='группа'),
        ),
    ]