# Generated by Django 4.2.5 on 2023-10-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_price_lesson_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateField(auto_now=True, null=True, verbose_name='последнее обновление'),
        ),
    ]