# Generated by Django 4.2.5 on 2023-10-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_course_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='последнее обновление'),
        ),
    ]