# Generated by Django 4.2.5 on 2023-10-13 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_course_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='last_update',
            field=models.CharField(blank=True, default=datetime.datetime(2023, 10, 13, 13, 22, 54, 195345), max_length=50, null=True, verbose_name='последнее обновление'),
        ),
    ]