# Generated by Django 4.2.7 on 2023-11-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_alter_course_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='last_update',
        ),
    ]
